### ISSUE TITLE
Backup and/or Copy Videos 

### ISSUE THREAD

**Issue by techteam25** [techteam25/SPadv#75]
Enable from the Main Menu a function to Backup or Copy the Videos folder to a designated location (e.g. internal storage, SD card, OTG flash drive, computer). 
It would be helpful if, in the Videos folder, all the 3pg files went into their own designated folder and all the mp4 files went into a designated folder.  (This would enable the android device to more easily be utilized as a micro-SD card copier for distributing to mobile phone holders.

**Comment by RobinRempel** [comment]
This is a good question.  One which we have discussed and tried to cater for in the process of developing SP app.  We do want to have an easy way for the SPadv user to backup and/or copy the Video folder ... either for safe keeping or for mass distribution (e.g. copying to Scripture Earth for online availability; copying to SD cards).  
The thought was to have a link (in the main sidebar menu and also in the Share phase) to the Video folder in the SPworkspace folder.  But, a static/automated link is not possible since it is the user's choice where to put the SPworkspace folder.   The interim solution was to have a button in the Share phase that gives the user a non-linked map to where the Video folder might be. 
When the installation of SPadv and templates gets more automated, then perhaps a link for copying/backing up videos can be developed.

**Comment by techteam25** [comment]
Think through various backups/copy options which a user might want:  
- backup of user audio and story.json files
- sync with another phone doing work on the same language project
- backup/copy video Folder (... to a drive, to local storage or SD card, upload to a google drive etc)

Discussion sheet [https://docs.google.com/document/d/1kCouHYba8S7eew5qXJSUGwSJWH0wN2tmHaIlgke82vk/edit?usp=sharing](url)
-

**Comment by tkmeadows** [comment]
done
