### ISSUE TITLE
Email to ROCCer; Notice to SP translator

### ISSUE THREAD

**Issue by techteam25** [techteam25/SPadv#82]
Send an email to translator when approval for all slides has been made on ROCC

**Comment by RobinRempel** [comment]
Rather than an email, it would be more helpful to send a notice via the rSPadv app ... Perhaps a green dot (or something like that) on the story title in the Story Templates list ??  
And, it would be good if rSPadv interface for the approved story automatically scrolled down to the now unlocked Voice Studio phase.

**Comment by RobinRempel** [comment]
Thinking in the other direction, in addition to a notice for the SPadv translator, it would be helpful for ROCC to send an **email** notification to the consultant when a new story is ready for them to check.

**Comment by tkmeadows** [comment]
Related to communication between ROCC and SPadv users:

- The notice within SPadv for user to know everything is approved makes sense and we understand what needs done.

- Related to sending an email to ROCC consultant when a story is "ready for them to check....   What constitutes "Ready"?  Do all the recordings have to be there for all slides (obviously NOT the credits and song)?  If not, what?

@RobinRempel

**Comment by RobinRempel** [comment]
I think "ready"  could best be defined by having **uploaded 50% of the slide tell back** audio files.  
I have reasons for this, but perhaps you are not so interested in them.  Can a percentage work?
@tkmeadows

**Comment by tkmeadows** [comment]
Yes, 50% will work fine, but it leads to at least one additional question... perhaps more.

When the translation team uploads more audio file(s) after the 50% mark, does the consultant get another email?  
Or... is it enough to know that they are that far and the consultant needs to check periodically for more after the initial email?  
Or... don't send any more emails unless the consultant has logged in since the previous email was sent?
Or... perhaps some other variation you can think of?

@RobinRempel

**Comment by RobinRempel** [comment]
Good questions.  How about something like this:

- An email notice to the ROCCer at the 50% mark
- Another email notice at the 95% mark, whether or not the ROCCer has logged in. 
- If the ROCCer has not logged in for 3 days after these notices, then they get another email notice every 4 days until they do log in.  And the ROCCer's admin should be copied on all these final notices.
@tkmeadows  Do you think this would cover things?  The goal being that the remSPadv user does not get left hanging for too long without a ROCCer helping them to finish/approve their story.

**Comment by tkmeadows** [comment]
Yes, that clarifies things and seems to cover it better than "send an email".  When I see that kind of blanket statement for something like this I know there is/could be/should be a lot more behind it than just "just an email".  Thanks!

@RobinRempel

**Comment by RobinRempel** [comment]
In testing this feature with the v2.2 apk, I am registered as the Accuracy Checker and able to access the translated story on ROCC, but I am not receiving any notice emails.

**Comment by tkmeadows** [comment]
There is a new issue for adding the notification dot to the story template so the SPadv user knows a message came from the ROCC user.
