### ISSUE TITLE
Flag Community comment in Translate phase

### ISSUE THREAD

**Issue by RobinRempel** [techteam25/SPadv#94]
A field user in Indonesia suggested to enhance the UI/UX by putting a flag/notice in the Translate+Revise phase when there is a comment or comments made for a slide in the Community Work phase.  
Perhaps when a comment(s) is recorded in the Community phase a yellow-green dot (the same color as the Community phase) could appear in the Translate screen just above the recording bar at the bottom of the screen.  To resolve the notice flag, the user would delete all/any comments in the Community phase for that particular slide, then the notice flag in Translate would disappear.

**Comment by J-Daniel-S** [comment]
Preliminary working version present on commentIcon branch.  Need to add logic so that it displays properly when slides are changed.  icon is currently present in fragment_slide.xml and code governing visibility is currently in MultiRecordFrag.kt.

**Comment by J-Daniel-S** [comment]
Working on making the Boolean added to Workspace.kt to indicate comment presence an observable property so that it is automatically checked every time it is changed.

If I want Workspace to handle the (pseudo code) commentIcon.makeVisible() function it would have to be static.  It cannot be static because it requires access to the instance of the app that is running.  Unless I'm missing something the only option remaining is to make the boolean that is checked and changed every time the slide is changed observable.   I will have to read up to make sure I do this properly.

**Comment by J-Daniel-S** [comment]
I am asking around kotlin slack for information on how ViewPager and onPageChangeListener work.  If I can find out which functions are run and in which order on a paging event I can change visibility.  I can't figure it out because I can't get anything to print in Logcat.  Once they tell me this I should be cooking.

**Comment by J-Daniel-S** [comment]
Moved the icon to the toolbar and did away with the workspace boolean for now.  A simple list check is used in an if statement on the 169th line of RecordingToolbar.kt to either add the icon or not as appropriate.  For now it is present on all phases the toolbar is present on.  Let me know if it should disappear on the community work phase as it is redundant there.

**Comment by RobinRempel** [comment]
Dan, can you attach screenshot(s) for what this looks like?  We only need a
flag in Translate and Accuracy Check phases.

**Comment by J-Daniel-S** [comment]
That'll be an easy change.  I placed it in the toolbar per a discussion on our end but I can move it if need be.  Alternatively it can appear in the toolbar on the translate phase and near to the same location on the accuracy phase.  Right now it's on the bottom left hand of the screen.

**Comment by RobinRempel** [comment]
I'd be inclined to locate the flag to the lower right hand of the screen, on the Translate tool bar (to the right of the list play icon) and near the same location on the accuracy phase (to the right of the circle check icon).  
What does the flag look like?  (Just a dot?)   
What color is it?  (I'd suggest to make the flag the avocado green color of the Community phase.) 
A screen shot would be nice...

**Comment by J-Daniel-S** [comment]
![Image](https://user-images.githubusercontent.com/59487880/228098240-51cad488-d162-4efb-93aa-f757f44b1c0e.jpg)
![Image](https://user-images.githubusercontent.com/59487880/228098239-de892665-5d49-49d1-ae0e-e7d640ee1c3d.jpg)

The dot is on the bottom left for now.  It can be easily enough moved.  I am finally making headway on the slide issue so I'm going to make sure that functionality is working first.

**Comment by RobinRempel** [comment]
Dan, I'm thinking for the flags to be more **discreet** (smaller) and out of the way, and to show multiple comments if there are multiple comments. I don't think there is a need to change the Translation recording/tool bar.  Just add the flags to the far right side.  Here's a picture of what I think would be better UI:
![Comm flags Tr+Rev](https://user-images.githubusercontent.com/98855936/228257097-0e73b430-76bf-4783-b01c-538672c7ce37.png)

![Comm flags Acc Chk](https://user-images.githubusercontent.com/98855936/228258404-00e85586-9550-4c57-9fd0-435190a4d811.png)
