### ISSUE TITLE
Evaluate space on phone before download templates

### ISSUE THREAD

**Issue by techteam25** [techteam25/SPadv#98]
Test how much free space is on the phone before downloading templates.  If less than 4gb of space is free, tell the user how much space they have AND tell them "it is best to have 1gb of space available per template you will be working on."

**Comment by raykaestner** [comment]
I have started on this one.

**Comment by raykaestner** [comment]
Here is the proposed warning message for possibly not enough space.

![Image](https://user-images.githubusercontent.com/123203572/233712981-ec0bf632-0554-47f3-bc4d-6f18ab721287.png)

**Comment by raykaestner** [comment]
I have a couple of questions on this one.

- The message says that it is recommended to have "1gb of space available per
template you will be working on".  In my limited testing, the templates I 
was downloading were much less than 1gb, so I was guessing that the 1gb
recommendation is to allow space for the content created by our users.  Is that
correct?  Does the warning message adequately convey that information?

- Issue 98 says to put up the warning message if there are less than 4gb 
of available space.  If you only have 1 template selected, that seems like the
warning may be unnecessary unless you are closer to 1gb of free space.  Would it
be better to give the warning if the free space is less than the quantity of  1gb * the number
of selected templates?   In my current fix, if they have more than 4 templates 
selected I will bump up the need for available space accordingly.

- Since I have added some new translatable strings to strings.xml, I was 
wondering about the process for translating the strings to the other languages.

**Comment by raykaestner** [comment]
See the following branch
https://github.com/techteam25/SPadv/tree/rkaestner/23apr05
